export const cmsRoutes = {
  login: 'login',
  forgotPassword: 'forgot-password',
  resetPassword: 'reset-password',
  dashboard: 'dashboard',
  server: 'server',
  sources: 'sources',
  items: 'items',
  itemsFixQueue: 'fix-queue',
  itemsReviewQueue: 'review-queue',
  itemsByCategory: 'items-by-category',
  categories: 'categories',
  clients: 'clients',
  customerRemarks: 'customer-remarks',
  users: 'users',
  roles: 'roles',
  notifications: 'notifications',
  auditLog: 'audit-log',
  settings: 'settings',
} as const;
